### PR TITLE
Test cases and fix to SessionWebService

### PR DESCRIPTION
**Pull request by henrycg**
Hi David,

Do you want to take a look at this code and see what you think? I implemented the session hack for now and it seems to work just fine.

Henry

### CODE REVIEW

**Comment by davidiw** [comment]
Looks good, two minor gripes
- Remove the default print connections from the ConnectionTable
- Even with the inclusion of local-web.conf are you still adamant about conf/web ? please please please ... if not I acquiesce

**Comment by henrycg** [comment]
Ok, I removed conf/web.

**Comment by davidiw** [comment]
Pulled, could you disable the std out printed in the tests (about where the web server is).  I'd eventually like to see a shutdown dissent webservice.

**Comment by henrycg** [comment]
On 12/09/2011 07:51 PM, davidiw wrote:

> Pulled, could you disable the std out printed in the tests (about where the web server is).  I'd eventually like to see a shutdown dissent webservice.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davidiw/Dissent/pull/4#issuecomment-3088291

I use the stdin/stdout stuff to communicate with the server because it 
makes easier to test a clean shutdown with valgrind (by sending "quit" 
on stdin). Catching ctrl-C with Qt is not portable and also requires a 
lot of signal handling code.

**Pull request closed without merging**
